//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Project
{
    public long id { get; set; }
    public string description { get; set; }
    public Nullable<System.DateTime> created_at { get; set; }
    public Nullable<System.DateTime> modified_at { get; set; }
    public Nullable<int> status { get; set; }
    public Nullable<int> user_id { get; set; }
    public Nullable<int> upload_id { get; set; }
    public Nullable<int> proj_cat_id { get; set; }
    public string name { get; set; }
    public Nullable<int> exec_summary_id { get; set; }
    public Nullable<int> company_id { get; set; }
    public Nullable<int> policy_id { get; set; }
    public Nullable<int> methodology_id { get; set; }
    public string team { get; set; }
    public Nullable<int> proj_reference { get; set; }
    public Nullable<int> cost_plan_id { get; set; }
    public string conclusion { get; set; }
}
